<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>feedback</title>
    <link rel="stylesheet" href="../assets/css/main.css">
    <script src="../assets/js/main.js"></script>
</head>
<body>


<form action="" class="ajax-form">
    <input type="text" name="name" placeholder="Имя" required>
    <input type="tel" name="phone" placeholder="Телефон" required>
    <input type="email" name="email" placeholder="Email" required>
    <textarea name="message" placeholder="Текст сообщения" required></textarea>
    <input type="submit" value="отправить">
</form>


</body>
</html>
